[tool.black]
line-length = 99
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 99

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 99
target-version = "py38"
select = ["E9", "F401", "F7", "F82"]
fixable = ["ALL"]
show-source = true
