name: Checks

on: [push, pull_request]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        linter: [black, isort, ruff]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install
        run: |
        if [ "${{ matrix.linter }}" == "isort" ]; then
          python -m pip install isort[colors]
        else
          python -m pip install ${{ matrix.linter }}
        fi
      - name: Check
        run: |
        if [ "${{ matrix.linter }}" == "ruff" ]; then
          python -m ruff check .
        else
          python -m ${{ matrix.linter }} --check --color --diff .
        fi