name: Tests

on: [push, pull_request]

env:
  ref: ${{ github.event.client_payload.ref || '' }}

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - "3.10"
          - "3.11"
          - "3.12"
    name: Python ${{ matrix.python_version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.ref }}
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Compile
        run: python -m compileall .